import { Terminal, TerminalInfo } from '../types/terminals';

export const terminals: Terminal[] = [
  {
    id: '1',
    name: 'PAO01',
    status: true,
    branch: 'Parking, 1st floor, gate Bуаукауаукпукпукпукпкукпукпупукпукп',
    updated: '2025-05-27T13:33:26',
    amountEUR: 23000,
    amountCZK: 85000,
  },
  {
    id: '2',
    name: 'TCS02',
    status: false,
    branch: 'Main Entrance, kiosk 3',
    updated: '2025-05-27T14:15:00',
    amountEUR: 15500,
    amountCZK: 42000,
    notification: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean posuere fringilla ex vel vulputate. Vivamus tincidunt sed dolor tempor consequat. Proin ac sapien odio.',
    ],
  },
  {
    id: '3',
    name: 'BRC03',
    status: true,
    branch: 'Building C, cafeteria',
    updated: '2025-05-28T09:00:10',
    amountEUR: 31000,
    amountCZK: 115000,
    notification: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean posuere fringilla ex vel vulputate. Vivamus tincidunt sed dolor tempor consequat. Proin ac sapien odio.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean posuere fringilla ex vel vulputate. Vivamus tincidunt sed dolor tempor consequat. Proin ac sapien odio.',
    ],
  },
  {
    id: '4',
    name: 'MKT04',
    status: true,
    branch: 'Marketplace, stand 7',
    updated: '2025-05-28T11:45:30',
    amountEUR: 9800,
    amountCZK: 36000,
    notification: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean posuere fringilla ex vel vulputate. Vivamus tincidunt sed dolor tempor consequat. Proin ac sapien odio.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean posuere fringilla ex vel vulputate. Vivamus tincidunt sed dolor tempor consequat. Proin ac sapien odio.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean posuere fringilla ex vel vulputate. Vivamus tincidunt sed dolor tempor consequat. Proin ac sapien odio.',
    ],
  },
  {
    id: '5',
    name: 'HRD05',
    status: false,
    branch: 'Head Office, reception',
    updated: '2025-05-29T08:20:05',
    amountEUR: 18700,
    amountCZK: 69000,
  },
  {
    id: '6',
    name: 'WHS06',
    status: true,
    branch: 'Warehouse, loading dock',
    updated: '2025-05-29T16:00:00',
    amountEUR: 45000,
    amountCZK: 167000,
  },
  {
    id: '7',
    name: 'RET07',
    status: true,
    branch: 'Retail Store A, cashier 1',
    updated: '2025-05-30T10:10:10',
    amountEUR: 12300,
    amountCZK: 45000,
  },
  {
    id: '8',
    name: 'RET08',
    status: false,
    branch: 'Retail Store B, cashier 2',
    updated: '2025-05-30T14:55:00',
    amountEUR: 7800,
    amountCZK: 28000,
  },
  {
    id: '9',
    name: 'SVC09',
    status: true,
    branch: 'Service Center, desk 4',
    updated: '2025-06-01T09:30:45',
    amountEUR: 27500,
    amountCZK: 102000,
  },
  {
    id: '10',
    name: 'RST10',
    status: true,
    branch: 'Restaurant, bar area',
    updated: '2025-06-01T20:00:00',
    amountEUR: 33000,
    amountCZK: 122000,
  },
  {
    id: '11',
    name: 'GYM11',
    status: false,
    branch: 'Gym, front desk',
    updated: '2025-06-02T07:15:20',
    amountEUR: 5500,
    amountCZK: 20000,
  },
  {
    id: '12',
    name: 'HTL12',
    status: true,
    branch: 'Hotel Lobby, concierge',
    updated: '2025-06-02T18:40:00',
    amountEUR: 48000,
    amountCZK: 178000,
  },
  {
    id: '13',
    name: 'LIB13',
    status: true,
    branch: 'Library, reading corner',
    updated: '2025-06-03T11:00:00',
    amountEUR: 1000,
    amountCZK: 3700,
  },
  {
    id: '14',
    name: 'TRM14',
    status: false,
    branch: 'Terminal Gate A5',
    updated: '2025-06-03T23:59:59',
    amountEUR: 65000,
    amountCZK: 240000,
  },
  {
    id: '15',
    name: 'CAR15',
    status: true,
    branch: 'Car Wash, self-service bay',
    updated: '2025-06-04T06:30:00',
    amountEUR: 2800,
    amountCZK: 10500,
  },
  {
    id: '16',
    name: 'OFC16',
    status: true,
    branch: 'Office 201, meeting room',
    updated: '2025-06-04T15:15:15',
    amountEUR: 19000,
    amountCZK: 70000,
  },
  {
    id: '17',
    name: 'FAC17',
    status: false,
    branch: 'Factory Floor, line 3',
    updated: '2025-06-05T09:00:00',
    amountEUR: 52000,
    amountCZK: 192000,
  },
  {
    id: '18',
    name: 'SHP18',
    status: true,
    branch: 'Shopping Mall, food court',
    updated: '2025-06-05T12:30:00',
    amountEUR: 21500,
    amountCZK: 79000,
  },
  {
    id: '19',
    name: 'RES19',
    status: true,
    branch: 'Residential Complex, lobby',
    updated: '2025-06-06T10:00:00',
    amountEUR: 13000,
    amountCZK: 48000,
  },
  {
    id: '20',
    name: 'SQR20',
    status: true,
    branch: 'City Square, information point',
    updated: '2025-06-06T17:00:00',
    amountEUR: 37000,
    amountCZK: 137000,
  },
];

export const terminalInfo: TerminalInfo = {
  id: '1',
  name: 'PAO01',
  status: true,
  branch: 'Parking, 1st floor, gate B',
  updated: '2025-05-27T13:33:26',
  amountEUR: 23000,
  amountCZK: 85000,

  stateOfMeans: [
    {
      denomination: 1,
      totalCount: 44,
      totalAmount: 44,
      countToBePaid: 44,
      amountToBePaid: 44,
      type: 'coin',
    },
    {
      denomination: 2,
      totalCount: 52,
      totalAmount: 104,
      countToBePaid: 52,
      amountToBePaid: 104,
      type: 'coin',
    },
    {
      denomination: 5,
      totalCount: 37,
      totalAmount: 185,
      countToBePaid: 37,
      amountToBePaid: 185,
      type: 'coin',
    },
    {
      denomination: 10,
      totalCount: 24,
      totalAmount: 240,
      countToBePaid: 24,
      amountToBePaid: 240,
      type: 'coin',
    },
    {
      denomination: 20,
      totalCount: 600,
      totalAmount: 30,
      countToBePaid: 600,
      amountToBePaid: 30,
      type: 'coin',
    },
    {
      denomination: 50,
      totalCount: 31,
      totalAmount: 1550,
      countToBePaid: 31,
      amountToBePaid: 1550,
      type: 'coin',
    },
    {
      denomination: 100,
      totalCount: 57,
      totalAmount: 5700,
      countToBePaid: 57,
      amountToBePaid: 5700,
      type: 'money',
    },
    {
      denomination: 200,
      totalCount: 28,
      totalAmount: 5600,
      countToBePaid: 26,
      amountToBePaid: 5600,
      type: 'money',
    },
    {
      denomination: 500,
      totalCount: 26,
      totalAmount: 13000,
      countToBePaid: 26,
      amountToBePaid: 13000,
      type: 'money',
    },
    {
      denomination: 1000,
      totalCount: 6,
      totalAmount: 6000,
      countToBePaid: 6,
      amountToBePaid: 6000,
      type: 'money',
    },
    {
      denomination: 2000,
      totalCount: 3,
      totalAmount: 6000,
      countToBePaid: 3,
      amountToBePaid: 6000,
      type: 'money',
    },
    {
      denomination: 5000,
      totalCount: 0,
      totalAmount: 0,
      countToBePaid: 0,
      amountToBePaid: 0,
      type: 'money',
    },
  ],

  coinRecycler: [
    {
      denomination: 1,
      totalCount: 44,
      totalAmount: 44,
      warningCount: 15,
      criticalCount: 5,
      maxCount: 100,
      type: 'coin',
    },
    {
      denomination: 2,
      totalCount: 52,
      totalAmount: 104,
      warningCount: 15,
      criticalCount: 5,
      maxCount: 100,
      type: 'coin',
    },
    {
      denomination: 1,
      totalCount: 44,
      totalAmount: 44,
      warningCount: 15,
      criticalCount: 5,
      maxCount: 100,
      type: 'coin',
    },
    {
      denomination: 2,
      totalCount: 52,
      totalAmount: 104,
      warningCount: 15,
      criticalCount: 5,
      maxCount: 100,
      type: 'coin',
    },
    {
      denomination: 1,
      totalCount: 44,
      totalAmount: 44,
      warningCount: 15,
      criticalCount: 5,
      maxCount: 100,
      type: 'coin',
    },
    {
      denomination: 2,
      totalCount: 52,
      totalAmount: 104,
      warningCount: 15,
      criticalCount: 5,
      maxCount: 100,
      type: 'coin',
    },
  ],
};
