import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const resources = {
  eng: {
    translation: {
      export: 'Export',
      terminal: 'Terminal',
      branch: 'Branch',
      time: 'State update time',
      update: 'Update',
      online: 'Online',
      apply: 'Apply',
      search: 'Search',
      terminalName: 'Terminal Name',
      branchName: 'Branch Name',
      statusName: 'Status',
      cash_state: 'Cash state',
      backBtn: 'Back',
      state_update_time: 'State update time',
      stateOfMeansOfPayment: 'State of means of payment',
      stateOfMeansOfPaymentInBoxes: 'State of means of payment in boxes',
      denomination: 'Denomination',
      totalCount: 'Total count',
      totalAmount: 'Total amount',
      countToBePaid: 'Count to be paid',
      amountToBePaid: 'Amount to be paid',
      warningCount: 'Warning Count',
      criticalCount: 'Critical Count',
      maxCount: 'Max count',
      coinRecycler: 'Coin recycler',
      total: 'Total',
    },
  },
  cz: {
    translation: {
      export: 'Export',
      terminal: 'Terminál',
      branch: 'Pobočka',
      time: 'Čas aktualizace stavu',
      update: 'Aktualizovat',
      online: 'Online',
      apply: 'Použít',
      search: 'Hledat',
      terminalName: 'Název terminálu',
      branchName: 'Název pobočky',
      statusName: 'Stav',
      cash_state: 'Stav hotovosti',
      backBtn: 'Zpět',
      state_update_time: 'Čas aktualizace stavu',
      stateOfMeansOfPayment: 'Stav platebních prostředků',
      stateOfMeansOfPaymentInBoxes: 'Stav platebních prostředků v boxech',
      denomination: 'Denominace',
      totalCount: 'Celkový počet',
      totalAmount: 'Celková částka',
      countToBePaid: 'Počet k výplatě',
      amountToBePaid: 'Částka k výplatě',
      warningCount: 'Varovný počet',
      criticalCount: 'Kritický počet',
      maxCount: 'Maximální počet',
      coinRecycler: 'Recyklátor mincí',
      total: 'Celkem',
    },
  },

  sk: {
    translation: {
      export: 'Export',
      terminal: 'Terminál',
      branch: 'Pobočka',
      time: 'Čas aktualizácie stavu',
      update: 'Aktualizovať',
      online: 'Online',
      apply: 'Použiť',
      search: 'Hľadať',
      terminalName: 'Názov terminálu',
      branchName: 'Názov pobočky',
      statusName: 'Stav',
      cash_state: 'Stav hotovosti',
      backBtn: 'Späť',
      state_update_time: 'Čas aktualizácie stavu',
      stateOfMeansOfPayment: 'Stav platobných prostriedkov',
      stateOfMeansOfPaymentInBoxes: 'Stav platobných prostriedkov v boxoch',
      denomination: 'Denominácia',
      totalCount: 'Celkový počet',
      totalAmount: 'Celková suma',
      countToBePaid: 'Počet na vyplatenie',
      amountToBePaid: 'Suma na vyplatenie',
      warningCount: 'Varovný počet',
      criticalCount: 'Kritický počet',
      maxCount: 'Maximálny počet',
      coinRecycler: 'Recyklátor mincí',
      total: 'Celkom',
    },
  },
};

i18n.use(initReactI18next).init({
  resources,
  lng: 'eng',
  fallbackLng: 'eng',
  debug: false,
  interpolation: {
    escapeValue: false,
  },
  react: {
    useSuspense: true,
  },
});

export default i18n;
